### ISSUE TITLE
Add git presentation

### ISSUE THREAD

**Issue by maxibor** [rrdm-shh/rrdm-shh.github.io#24]
Hey @chrzyki ,
Could you make a PR to add a link/integrate your (great !) presentation about git to the website ?
Since your slides are also in html, you can embed them directly on the website (like for the [bash](https://raw.githubusercontent.com/rrdm-shh/rrdm-shh.github.io/master/day1/intro_to_bash.md) and conda session)

**Comment by chrzyki** [comment]
Will do!

**Comment by chrzyki** [comment]
Done in #26
